// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitlab.com/gear5th/gear5th-app/internal/application"
	"gitlab.com/gear5th/gear5th-app/internal/application/adsinteractors"
	"gitlab.com/gear5th/gear5th-app/internal/application/advertiserinteractors"
	"gitlab.com/gear5th/gear5th-app/internal/application/identityinteractors"
	"gitlab.com/gear5th/gear5th-app/internal/application/paymentinteractors"
	"gitlab.com/gear5th/gear5th-app/internal/application/publisherinteractors"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/adslothtml"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/identity/googleoauth"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/identity/tokens"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/keyvaluestore/rediskeyvaluestore"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/mail"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/mail/disbursementemail"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/mail/identityemail"
	"gitlab.com/gear5th/gear5th-app/internal/infrastructure/siteverification"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/adspersistence/adclickrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/adspersistence/impressionrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/advertiserpersistence/adpiecerepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/advertiserpersistence/advertiserrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/advertiserpersistence/campaignrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/filestore"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/identitypersistence/manageduserrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/identitypersistence/oauthuserrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/identitypersistence/userrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/paymentpersistence/depositrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/paymentpersistence/disbursementrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/publisherpersistence/adslotrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/publisherpersistence/publisherrepository"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/publisherpersistence/publishersignupunitofwork"
	"gitlab.com/gear5th/gear5th-app/internal/persistence/mongodbpersistence/publisherpersistence/siterepository"
	"gitlab.com/gear5th/gear5th-app/web/controllers/admin/adminadvertisers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/admin/admindashboard"
	"gitlab.com/gear5th/gear5th-app/web/controllers/admin/adminidentity"
	"gitlab.com/gear5th/gear5th-app/web/controllers/admin/adminpublisherpayments"
	"gitlab.com/gear5th/gear5th-app/web/controllers/ads/adclickcontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/ads/adservercontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/ads/impressioncontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/advertiser/adpiececontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/advertiser/campaigncontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/accountcontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/adslotcontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/homecontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/identitycontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/paymentcontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/publishercontrollers"
	"gitlab.com/gear5th/gear5th-app/web/controllers/publish/sitecontrollers"
	"gitlab.com/gear5th/gear5th-app/web/events"
	"gitlab.com/gear5th/gear5th-app/web/middlewares"
)

// Injectors from dependecyproviders.go:

func InitJwtAuthenticationMiddleware() middlewares.JwtAuthenticationMiddleware {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	return jwtAuthenticationMiddleware
}

func InitManagedUserController() identitycontrollers.UserSignInController {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	requestPasswordResetEmailService := identityemail.NewRequestPasswordResetEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	managedUserInteractor := identityinteractors.NewManagedUserInteractor(inMemoryEventDispatcher, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, jwtAccessTokenService, requestPasswordResetEmailService, hs256HMACValidationService)
	userSignInController := identitycontrollers.NewUserSignInController(managedUserInteractor, appLogger)
	return userSignInController
}

func InitOAuthSignInController() identitycontrollers.OAuthSignInController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	mongoDBOAuthUserRepository := oauthuserrepository.NewMongoDBOAuthUserRepository(mongoDBStoreBootstrap)
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	googleOAuthServiceImpl := googleoauth.NewGoogleOAuthService()
	oAuthUserInteractor := identityinteractors.NewOAuthUserInteractor(mongoDBOAuthUserRepository, jwtAccessTokenService, googleOAuthServiceImpl)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	oAuthSignInController := identitycontrollers.NewOAuthSignInController(oAuthUserInteractor, appLogger)
	return oAuthSignInController
}

func InitPublisherSignUpController() publishercontrollers.PublisherSignUpController {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	mongoDBOAuthUserRepository := oauthuserrepository.NewMongoDBOAuthUserRepository(mongoDBStoreBootstrap)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	mongoDBPublisherSignUpUnitOfWork := publishersignupunitofwork.NewMongoDBPublisherSignUpUnitOfWork(mongoDBStoreBootstrap, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, mongoDBOAuthUserRepository, mongoDBPublisherRepository)
	googleOAuthServiceImpl := googleoauth.NewGoogleOAuthService()
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	publisherInteractor := publisherinteractors.NewPublisherInteractor(inMemoryEventDispatcher, mongoDBPublisherSignUpUnitOfWork, mongoDBUserRepositoryCached, mongoDBPublisherRepository, googleOAuthServiceImpl, appLogger)
	publisherSignUpController := publishercontrollers.NewPublisherSignUpController(publisherInteractor, appLogger)
	return publisherSignUpController
}

func InitRequestPasswordResetController() identitycontrollers.RequestPasswordResetController {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	requestPasswordResetEmailService := identityemail.NewRequestPasswordResetEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	managedUserInteractor := identityinteractors.NewManagedUserInteractor(inMemoryEventDispatcher, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, jwtAccessTokenService, requestPasswordResetEmailService, hs256HMACValidationService)
	requestPasswordResetController := identitycontrollers.NewRequestPasswordResetController(managedUserInteractor, appLogger)
	return requestPasswordResetController
}

func InitVerifyEmailController() identitycontrollers.VerifyEmailController {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	requestPasswordResetEmailService := identityemail.NewRequestPasswordResetEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	managedUserInteractor := identityinteractors.NewManagedUserInteractor(inMemoryEventDispatcher, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, jwtAccessTokenService, requestPasswordResetEmailService, hs256HMACValidationService)
	verifyEmailController := identitycontrollers.NewVerifyEmailController(managedUserInteractor, appLogger)
	return verifyEmailController
}

func InitResetPasswordController() identitycontrollers.ResetPasswordController {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	requestPasswordResetEmailService := identityemail.NewRequestPasswordResetEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	managedUserInteractor := identityinteractors.NewManagedUserInteractor(inMemoryEventDispatcher, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, jwtAccessTokenService, requestPasswordResetEmailService, hs256HMACValidationService)
	resetPasswordController := identitycontrollers.NewResetPasswordController(managedUserInteractor, appLogger)
	return resetPasswordController
}

func InitHomeController() homecontrollers.HomeController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	earningInteractor := paymentinteractors.NewEarningInteractor(adsInteractor, depositInteractor, mongoDBPublisherRepository, mongoDBSiteRepository, mongoDBImpressionRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	homeController := homecontrollers.NewHomeController(jwtAuthenticationMiddleware, earningInteractor, adsInteractor)
	return homeController
}

func InitSiteController() sitecontrollers.SiteController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	appHTTPClient := infrastructure.NewAppHTTPClient()
	adsTxtVerificationService := siteverification.NewAdsTxtVerificationService(appHTTPClient, appLogger)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	siteInteractor := publisherinteractors.NewSiteInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, adsTxtVerificationService, inMemoryEventDispatcher, appLogger)
	siteController := sitecontrollers.NewSiteController(jwtAuthenticationMiddleware, siteInteractor, appLogger)
	return siteController
}

func InitCreateSiteController() sitecontrollers.CreateSiteController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	appHTTPClient := infrastructure.NewAppHTTPClient()
	adsTxtVerificationService := siteverification.NewAdsTxtVerificationService(appHTTPClient, appLogger)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	siteInteractor := publisherinteractors.NewSiteInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, adsTxtVerificationService, inMemoryEventDispatcher, appLogger)
	createSiteController := sitecontrollers.NewCreateSiteController(jwtAuthenticationMiddleware, siteInteractor, appLogger)
	return createSiteController
}

func InitVerifySiteController() sitecontrollers.VerifySiteController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	appHTTPClient := infrastructure.NewAppHTTPClient()
	adsTxtVerificationService := siteverification.NewAdsTxtVerificationService(appHTTPClient, appLogger)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	siteInteractor := publisherinteractors.NewSiteInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, adsTxtVerificationService, inMemoryEventDispatcher, appLogger)
	verifySiteController := sitecontrollers.NewVerifySiteController(jwtAuthenticationMiddleware, siteInteractor, appLogger)
	return verifySiteController
}

func InitAdSlotController() adslotcontrollers.AdSlotController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	adSlotHTMLSnippetService := adslothtml.NewAdSlotHTMLSnippetService(envConfigurationProvider)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adSlotInteractor := publisherinteractors.NewAdSlotInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, mongoDBAdSlotRepository, adSlotHTMLSnippetService, inMemoryEventDispatcher)
	adSlotController := adslotcontrollers.NewAdSlotController(jwtAuthenticationMiddleware, adSlotInteractor, appLogger)
	return adSlotController
}

func InitCreateAdSlotController() adslotcontrollers.CreateAdSlotController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	adSlotHTMLSnippetService := adslothtml.NewAdSlotHTMLSnippetService(envConfigurationProvider)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adSlotInteractor := publisherinteractors.NewAdSlotInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, mongoDBAdSlotRepository, adSlotHTMLSnippetService, inMemoryEventDispatcher)
	appHTTPClient := infrastructure.NewAppHTTPClient()
	adsTxtVerificationService := siteverification.NewAdsTxtVerificationService(appHTTPClient, appLogger)
	siteInteractor := publisherinteractors.NewSiteInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, adsTxtVerificationService, inMemoryEventDispatcher, appLogger)
	createAdSlotController := adslotcontrollers.NewCreateAdSlotController(jwtAuthenticationMiddleware, adSlotInteractor, siteInteractor, appLogger)
	return createAdSlotController
}

func InitEditAdSlotController() adslotcontrollers.EditAdSlotController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	adSlotHTMLSnippetService := adslothtml.NewAdSlotHTMLSnippetService(envConfigurationProvider)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adSlotInteractor := publisherinteractors.NewAdSlotInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, mongoDBAdSlotRepository, adSlotHTMLSnippetService, inMemoryEventDispatcher)
	editAdSlotController := adslotcontrollers.NewEditAdSlotController(jwtAuthenticationMiddleware, adSlotInteractor, appLogger)
	return editAdSlotController
}

func InitAdSlotIntegrationSnippetController() adslotcontrollers.AdSlotIntegrationSnippetController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	adSlotHTMLSnippetService := adslothtml.NewAdSlotHTMLSnippetService(envConfigurationProvider)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adSlotInteractor := publisherinteractors.NewAdSlotInteractor(mongoDBSiteRepository, mongoDBUserRepositoryCached, mongoDBAdSlotRepository, adSlotHTMLSnippetService, inMemoryEventDispatcher)
	adSlotIntegrationSnippetController := adslotcontrollers.NewAdSlotIntegrationSnippetController(jwtAuthenticationMiddleware, adSlotInteractor, appLogger)
	return adSlotIntegrationSnippetController
}

func InitAccountController() accountcontrollers.AccountController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	userAccountInteractor := identityinteractors.NewUserAccountInteractor(mongoDBUserRepositoryCached, mongoDBMangageUserRepository)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	accountController := accountcontrollers.NewAccountController(jwtAuthenticationMiddleware, userAccountInteractor, appLogger)
	return accountController
}

func InitAdPieceController() adpiececontrollers.AdPieceController {
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	advertiserRefferalMiddleware := middlewares.NewAdvertiserRefferalMiddleware(hs256HMACValidationService)
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adPieceInteractor := advertiserinteractors.NewAdPieceInteractor(mongoDBAdPieceRepository, mongoDBCampaignRepository, mongoDBUserRepositoryCached, inMemoryEventDispatcher)
	mongoDBGridFSFileStore := filestore.NewMongoDBGridFSFileStore(mongoDBStoreBootstrap)
	campaignInteractor := advertiserinteractors.NewCampaignInteractor(mongoDBCampaignRepository, mongoDBUserRepositoryCached, mongoDBAdPieceRepository, mongoDBGridFSFileStore, inMemoryEventDispatcher)
	adPieceController := adpiececontrollers.NewAdPieceController(advertiserRefferalMiddleware, adPieceInteractor, campaignInteractor, mongoDBGridFSFileStore, appLogger)
	return adPieceController
}

func InitAddAdPieceController() adpiececontrollers.AddAdPieceController {
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	advertiserRefferalMiddleware := middlewares.NewAdvertiserRefferalMiddleware(hs256HMACValidationService)
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adPieceInteractor := advertiserinteractors.NewAdPieceInteractor(mongoDBAdPieceRepository, mongoDBCampaignRepository, mongoDBUserRepositoryCached, inMemoryEventDispatcher)
	mongoDBGridFSFileStore := filestore.NewMongoDBGridFSFileStore(mongoDBStoreBootstrap)
	campaignInteractor := advertiserinteractors.NewCampaignInteractor(mongoDBCampaignRepository, mongoDBUserRepositoryCached, mongoDBAdPieceRepository, mongoDBGridFSFileStore, inMemoryEventDispatcher)
	addAdPieceController := adpiececontrollers.NewAddAdPieceController(advertiserRefferalMiddleware, adPieceInteractor, campaignInteractor, mongoDBGridFSFileStore, appLogger)
	return addAdPieceController
}

func InitCampaignController() campaigncontrollers.CampaignController {
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	advertiserRefferalMiddleware := middlewares.NewAdvertiserRefferalMiddleware(hs256HMACValidationService)
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBGridFSFileStore := filestore.NewMongoDBGridFSFileStore(mongoDBStoreBootstrap)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	campaignInteractor := advertiserinteractors.NewCampaignInteractor(mongoDBCampaignRepository, mongoDBUserRepositoryCached, mongoDBAdPieceRepository, mongoDBGridFSFileStore, inMemoryEventDispatcher)
	mongoDBAdvertiserRepository := advertiserrepository.NewMongoDBAdvertiserRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdvertiserSignUpUnitOfWork := advertiserrepository.NewMongoDBAdvertiserSignUpUnitOfWork(mongoDBAdvertiserRepository, mongoDBUserRepositoryCached, mongoDBStoreBootstrap, appLogger)
	advertiserInteractor := advertiserinteractors.NewAdvertiserInteractor(mongoDBAdvertiserRepository, mongoDBUserRepositoryCached, mongoDBAdvertiserSignUpUnitOfWork, hs256HMACValidationService, inMemoryEventDispatcher)
	campaignController := campaigncontrollers.NewCampaignController(advertiserRefferalMiddleware, campaignInteractor, advertiserInteractor, mongoDBGridFSFileStore, appLogger)
	return campaignController
}

func InitAdServerController() adservercontrollers.AdServerController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	adsPool := adsinteractors.NewAdsPool(redisKeyValueStore, mongoDBCampaignRepository, mongoDBAdPieceRepository, hs256HMACValidationService, appLogger)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	adServerController := adservercontrollers.NewAdServerController(adsPool, adsInteractor, appLogger)
	return adServerController
}

func InitAdClickController() adclickcontrollers.AdClickController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adPieceInteractor := advertiserinteractors.NewAdPieceInteractor(mongoDBAdPieceRepository, mongoDBCampaignRepository, mongoDBUserRepositoryCached, inMemoryEventDispatcher)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	adClickController := adclickcontrollers.NewAdClickController(adPieceInteractor, adsInteractor, appLogger)
	return adClickController
}

func InitImpressionController() impressioncontrollers.ImpressionController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adPieceInteractor := advertiserinteractors.NewAdPieceInteractor(mongoDBAdPieceRepository, mongoDBCampaignRepository, mongoDBUserRepositoryCached, inMemoryEventDispatcher)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	impressionController := impressioncontrollers.NewImpressionController(adPieceInteractor, adsInteractor, appLogger)
	return impressionController
}

func InitPaymentController() paymentcontrollers.PaymentController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	earningInteractor := paymentinteractors.NewEarningInteractor(adsInteractor, depositInteractor, mongoDBPublisherRepository, mongoDBSiteRepository, mongoDBImpressionRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBDisbursementRepository := disbursementrepository.NewMongoDBDisbursementRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	disbursementEmailService := disbursementemail.NewDisbursementEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	disbursementInteractor := paymentinteractors.NewDisbursementInteractor(mongoDBDisbursementRepository, mongoDBUserRepositoryCached, mongoDBPublisherRepository, earningInteractor, disbursementEmailService, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	paymentController := paymentcontrollers.NewPaymentController(jwtAuthenticationMiddleware, earningInteractor, disbursementInteractor, appLogger)
	return paymentController
}

func InitDisbursementController() paymentcontrollers.DisbursementController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	jwtAuthenticationMiddleware := middlewares.NewJwtAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	earningInteractor := paymentinteractors.NewEarningInteractor(adsInteractor, depositInteractor, mongoDBPublisherRepository, mongoDBSiteRepository, mongoDBImpressionRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBDisbursementRepository := disbursementrepository.NewMongoDBDisbursementRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	disbursementEmailService := disbursementemail.NewDisbursementEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	disbursementInteractor := paymentinteractors.NewDisbursementInteractor(mongoDBDisbursementRepository, mongoDBUserRepositoryCached, mongoDBPublisherRepository, earningInteractor, disbursementEmailService, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	disbursementController := paymentcontrollers.NewDisbursementController(jwtAuthenticationMiddleware, earningInteractor, disbursementInteractor, appLogger)
	return disbursementController
}

func InitAdminIdentityController() adminidentity.AdminIdentityController {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	requestPasswordResetEmailService := identityemail.NewRequestPasswordResetEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	managedUserInteractor := identityinteractors.NewManagedUserInteractor(inMemoryEventDispatcher, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, jwtAccessTokenService, requestPasswordResetEmailService, hs256HMACValidationService)
	adminIdentityController := adminidentity.NewAdminIdentityController(managedUserInteractor, appLogger)
	return adminIdentityController
}

func InitAdminDashboardController() admindashboard.AdminDashboardController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	adminAuthenticationMiddleware := middlewares.NewAdminAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	earningInteractor := paymentinteractors.NewEarningInteractor(adsInteractor, depositInteractor, mongoDBPublisherRepository, mongoDBSiteRepository, mongoDBImpressionRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	adminDashboardController := admindashboard.NewAdminDashboardController(adminAuthenticationMiddleware, adsInteractor, depositInteractor, earningInteractor, appLogger)
	return adminDashboardController
}

func InitAdminPublisherPaymentsController() adminpublisherpayments.AdminPublisherPaymentsController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	adminAuthenticationMiddleware := middlewares.NewAdminAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBDisbursementRepository := disbursementrepository.NewMongoDBDisbursementRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	earningInteractor := paymentinteractors.NewEarningInteractor(adsInteractor, depositInteractor, mongoDBPublisherRepository, mongoDBSiteRepository, mongoDBImpressionRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	disbursementEmailService := disbursementemail.NewDisbursementEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	disbursementInteractor := paymentinteractors.NewDisbursementInteractor(mongoDBDisbursementRepository, mongoDBUserRepositoryCached, mongoDBPublisherRepository, earningInteractor, disbursementEmailService, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	adminPublisherPaymentsController := adminpublisherpayments.NewAdminPublisherPaymentsController(adminAuthenticationMiddleware, adsInteractor, depositInteractor, disbursementInteractor, earningInteractor, appLogger)
	return adminPublisherPaymentsController
}

func InitAdminAdvertisersController() adminadvertisers.AdminAdvertisersController {
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	jwtAccessTokenService := tokens.NewJwtAccessTokenService(envConfigurationProvider)
	adminAuthenticationMiddleware := middlewares.NewAdminAuthenticationMiddleware(jwtAccessTokenService)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBAdvertiserRepository := advertiserrepository.NewMongoDBAdvertiserRepository(mongoDBStoreBootstrap, appLogger)
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	mongoDBAdvertiserSignUpUnitOfWork := advertiserrepository.NewMongoDBAdvertiserSignUpUnitOfWork(mongoDBAdvertiserRepository, mongoDBUserRepositoryCached, mongoDBStoreBootstrap, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	advertiserInteractor := advertiserinteractors.NewAdvertiserInteractor(mongoDBAdvertiserRepository, mongoDBUserRepositoryCached, mongoDBAdvertiserSignUpUnitOfWork, hs256HMACValidationService, inMemoryEventDispatcher)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBGridFSFileStore := filestore.NewMongoDBGridFSFileStore(mongoDBStoreBootstrap)
	campaignInteractor := advertiserinteractors.NewCampaignInteractor(mongoDBCampaignRepository, mongoDBUserRepositoryCached, mongoDBAdPieceRepository, mongoDBGridFSFileStore, inMemoryEventDispatcher)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	adminAdvertisersController := adminadvertisers.NewAdminAdvertisersController(adminAuthenticationMiddleware, advertiserInteractor, campaignInteractor, depositInteractor, appLogger)
	return adminAdvertisersController
}

func InitEventsRegistrar() events.EventHandlerRegistrar {
	inMemoryEventDispatcher := application.NewAppEventDispatcher()
	envConfigurationProvider := infrastructure.NewEnvConfigurationProvider()
	redisBootstrapper := rediskeyvaluestore.NewRedisBootstrapper(envConfigurationProvider)
	redisKeyValueStore := rediskeyvaluestore.NewRedisKeyValueStore(redisBootstrapper)
	mongoDBStoreBootstrap := mongodbpersistence.NewMongoDBStoreBootstrap(envConfigurationProvider)
	appLogger := infrastructure.NewAppLogger(envConfigurationProvider)
	mongoDBCampaignRepository := campaignrepository.NewMongoDBCampaignRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdPieceRepository := adpiecerepository.NewMongoDBAdPieceRepository(mongoDBStoreBootstrap, appLogger)
	hs256HMACValidationService := tokens.NewHS256HMACValidationService()
	adsPool := adsinteractors.NewAdsPool(redisKeyValueStore, mongoDBCampaignRepository, mongoDBAdPieceRepository, hs256HMACValidationService, appLogger)
	mongoDBImpressionRepository := impressionrepository.NewMongoDBImpressionRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdClickRepository := adclickrepository.NewMongoDBAdClickRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBSiteRepository := siterepository.NewMongoDBSiteRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBAdSlotRepository := adslotrepository.NewMongoDBAdSlotRepository(mongoDBStoreBootstrap, appLogger)
	adsInteractor := adsinteractors.NewAdsInteractor(mongoDBImpressionRepository, mongoDBAdClickRepository, mongoDBSiteRepository, mongoDBAdSlotRepository, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBDepositRepository := depositrepository.NewMongoDBDepositRepository(mongoDBStoreBootstrap, appLogger)
	depositInteractor := paymentinteractors.NewDepositInteractor(mongoDBDepositRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBPublisherRepository := publisherrepository.NewMongoDBPublisherRepository(mongoDBStoreBootstrap)
	earningInteractor := paymentinteractors.NewEarningInteractor(adsInteractor, depositInteractor, mongoDBPublisherRepository, mongoDBSiteRepository, mongoDBImpressionRepository, redisKeyValueStore, inMemoryEventDispatcher, appLogger)
	mongoDBDisbursementRepository := disbursementrepository.NewMongoDBDisbursementRepository(mongoDBStoreBootstrap, appLogger)
	mongoDBUserRepositoryCached := userrepository.NewMongoDBUserRepositoryCached(mongoDBStoreBootstrap, redisKeyValueStore)
	smtpMailSender := mail.NewSMTPMailSender(envConfigurationProvider, appLogger)
	disbursementEmailService := disbursementemail.NewDisbursementEmailService(envConfigurationProvider, smtpMailSender, hs256HMACValidationService, appLogger)
	disbursementInteractor := paymentinteractors.NewDisbursementInteractor(mongoDBDisbursementRepository, mongoDBUserRepositoryCached, mongoDBPublisherRepository, earningInteractor, disbursementEmailService, redisKeyValueStore, hs256HMACValidationService, inMemoryEventDispatcher, appLogger)
	mongoDBMangageUserRepository := manageduserrepository.NewMongoDBMangageUserRepository(mongoDBStoreBootstrap)
	mongoDBOAuthUserRepository := oauthuserrepository.NewMongoDBOAuthUserRepository(mongoDBStoreBootstrap)
	mongoDBPublisherSignUpUnitOfWork := publishersignupunitofwork.NewMongoDBPublisherSignUpUnitOfWork(mongoDBStoreBootstrap, mongoDBUserRepositoryCached, mongoDBMangageUserRepository, mongoDBOAuthUserRepository, mongoDBPublisherRepository)
	googleOAuthServiceImpl := googleoauth.NewGoogleOAuthService()
	publisherInteractor := publisherinteractors.NewPublisherInteractor(inMemoryEventDispatcher, mongoDBPublisherSignUpUnitOfWork, mongoDBUserRepositoryCached, mongoDBPublisherRepository, googleOAuthServiceImpl, appLogger)
	verificationEmailSender := identityemail.NewVerifcationEmailSender(envConfigurationProvider, hs256HMACValidationService, smtpMailSender, appLogger)
	verificationEmailInteractor := identityinteractors.NewVerificationEmailInteractor(verificationEmailSender, appLogger)
	eventHandlerRegistrar := events.NewEventHandlerRegistrar(inMemoryEventDispatcher, adsPool, adsInteractor, depositInteractor, earningInteractor, disbursementInteractor, publisherInteractor, verificationEmailInteractor)
	return eventHandlerRegistrar
}
