// Code generated by "stringer --type AuthenticationMethod"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Email-0]
	_ = x[GoogleOAuth-1]
}

const _AuthenticationMethod_name = "EmailGoogleOAuth"

var _AuthenticationMethod_index = [...]uint8{0, 5, 16}

func (i AuthenticationMethod) String() string {
	if i < 0 || i >= AuthenticationMethod(len(_AuthenticationMethod_index)-1) {
		return "AuthenticationMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthenticationMethod_name[_AuthenticationMethod_index[i]:_AuthenticationMethod_index[i+1]]
}
