// Code generated by "stringer --type UserRole"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Administrator-0]
	_ = x[Publisher-1]
	_ = x[Advertiser-2]
}

const _UserRole_name = "AdministratorPublisherAdvertiser"

var _UserRole_index = [...]uint8{0, 13, 22, 32}

func (i UserRole) String() string {
	if i < 0 || i >= UserRole(len(_UserRole_index)-1) {
		return "UserRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserRole_name[_UserRole_index[i]:_UserRole_index[i+1]]
}
